name: Continuous integration workflow

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./web

jobs:

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npx standard -v
        